# Generated by Django 5.0.4 on 2024-04-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationship',
            field=models.CharField(blank=True, choices=[('1', 'Single'), ('2', 'In a relationship'), ('3', 'Engaged'), ('4', 'Married'), ('5', 'In a civil union'), ('6', 'In an open relationship'), ('7', 'In a domestic partnership')], max_length=1, null=True),
        ),
    ]
