# Generated by Django 5.0.4 on 2024-04-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_game_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DitailOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('discription', models.TextField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=20)),
                ('price', models.PositiveSmallIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.categoryofproduct')),
                ('ditail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.ditailofproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.user')),
            ],
        ),
    ]
