# Generated by Django 5.0.4 on 2024-04-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, unique=True),
        ),
    ]
