# Generated by Django 5.0.4 on 2024-04-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listam', '0003_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('views', models.SmallIntegerField()),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listam.subcategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listam.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/photo/')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listam.subcategory')),
            ],
        ),
    ]
