# Generated by Django 5.0.4 on 2024-04-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listam', '0004_ads_adsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Massages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ads_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listam.ads')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listam.user')),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attended_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listam.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listam.payment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listam.user')),
            ],
        ),
    ]
